# Note: You can configure this Podfile to use the local CocoaPod included with the tutorials
#       or pull a version from github.  For production code you would normally reference
#       the github version.  For guaranteed compatibility with the tutorials, use the local version.

#       You may also choose to use widevine.

local = true
widevine = false

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

if !local
  source 'https://github.com/penthera/Cache-and-Carry-specs.git'
  source 'https://github.com/CocoaPods/Specs.git'
end

target 'Example9' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Example9

  if local
    if widevine
      pod 'VirtuosoClientDownloadEngineWidevine', :podspec => "../../Podspecs/VirtuosoClientDownloadEngineWidevine.podspec"
    else
      pod 'VirtuosoClientDownloadEngine', :podspec => "../../Podspecs/VirtuosoClientDownloadEngine.podspec"
    end
  else
    if widevine
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngineWidevine'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngineWidevine', '~> 4.00'
    else
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngine'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngine', '~> 4.00'
    end
  end

  puts "Using" + (local ? " local" : " github") + " version of VirtuosoClientDownloadEngine CocoaPod" + (widevine ? " for Widevine" : "") 

end
