# Note: You can configure this Podfile to use the local CocoaPod included with the tutorials
#       or pull a version from github.  For production code you would normally reference
#       the github version.  For guaranteed compatibility with the tutorials, use the local version.

#       You may also choose to use widevine.

local = true
widevine = false 

if !local
  source 'https://github.com/penthera/Download2Go-specs.git'
end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Download2Go_Hello_World' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  if local
    if widevine
      pod 'VirtuosoClientDownloadEngineWidevine', :podspec => "../../../Podspecs/VirtuosoClientDownloadEngineWidevine.podspec"
    else
      pod 'VirtuosoClientDownloadEngine', :podspec => "../../../Podspecs/VirtuosoClientDownloadEngine.podspec"
    end
  else
    if widevine
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngineWidevine'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngineWidevine', '~> 4.00'
    else
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngine'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngine', '~> 4.00'
    end
  end
  
  puts "Using" + (local ? " local" : " github") + " version of VirtuosoClientDownloadEngine CocoaPod" + (widevine ? " for Widevine" : "") 

  target 'Download2Go_Hello_WorldTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end