# Note: You can configure this Podfile to use the local CocoaPod included with the tutorials
#       or pull a version from github.  For production code you would normally reference
#       the github version.  For guaranteed compatibility with the tutorials, use the local version.

#       You may also choose to use bitcode.

local = true
bitcode = true # default for React-Native

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Download2GoHelloWorld React Native' do
  # Pods for Download2GoHelloWorld React Native
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  if local
    if bitcode
      pod 'VirtuosoClientDownloadEngine', :podspec => "../../../CocoaPodsConfig/VirtuosoClientDownloadEngineBitcode.podspec"
    else
      pod 'VirtuosoClientDownloadEngine', :podspec => "../../../CocoaPodsConfig/VirtuosoClientDownloadEngine.podspec"
    end
  else
    if bitcode
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngineBitcode'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngineBitcode', '~> 3.15.13'
    else
      # IMPORTANT - Include the most current Penthera SDK
      pod 'VirtuosoClientDownloadEngine'
      # ALTERNATIVE - Specify a specific version of Penthera SDK
      # pod 'VirtuosoClientDownloadEngine', '~> 3.15.13'
    end
  end

  puts "Using" + (local ? " local" : " github") + " version of VirtuosoClientDownloadEngine CocoaPod" + (bitcode ? " with bitcode" : "") 

  target 'Download2GoHelloWorld React NativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Download2GoHelloWorld React Native-tvOS' do
  # Pods for Download2GoHelloWorld React Native-tvOS

  target 'Download2GoHelloWorld React Native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
